- .gitignore
setting up the basic file structure to follow the MVC paradigm
> basic file structure

- db/schema.sql
- models/Group.js
- models/GroupList.js
- models/GroupUser.js
- models/Item.js
- models/index.js
- models/user.js
1. Set up schema.
2. Created models for groups, items, lists, and users.
3. Created junction models for group/user and group/list.
4. Defined model relationships in the index.js file.
There may be some syntax errors--this isn't tested yet. Currently there's a many-to-many relationship between groups and the users belonging to those groups. Additionally, there's a one-to-many relationship between users and the groups they own. It's possible a mistake was made in that setup, as it's very confusing.
> schema and model setup

- .env.EXAMPLE
- config/connection.js
- server.js
This PR sets up the server.js file and connection.js file to login to our database and listen for requests.
> Server and Database Connection

- package.json
This PR adds bcrypt and express-handlebars packages.
> bcrypt and express-handlebars packages

- controllers/api/group-routes.js
- controllers/api/item-routes.js
- controllers/api/list-routes.js
- controllers/api/user-routes.js
This PR adds a exported router to each route file.
> Routes fix

- package.json
This PR adds handlebars to npm dependencies.
> Added handlebars to dependencies

- controllers/home-routes.js
- controllers/index.js
- server.js
- views/homepage.handlebars
- views/layouts/main.handlebars
This PR implements handlebars as our view engine and adds routes to the handlebars views.
> Home routes

- controllers/home-routes.js
- views/homepage.handlebars
- views/layouts/main.handlebars
This PR adds code to display groups on the homepage based on user_id.
> Homepage route

- controllers/api/user-routes.js
- package.json
- server.js
This PR implements session allowing the use of cookies to save login data.
> Login session

- controllers/api/user-routes.js
- server.js
- views/layouts/main.handlebars
- views/login.handlebars
This PR changes the default styling to dark and saves session when a new user is created.
> Header style

- controllers/api/user-routes.js
- models/user.js
- public/js/login.js
- views/login.handlebars
This PR adds a bcrypt hook and a check password function to the user model. It also adds all user-routes needed to login and fixes bugs with our front end.
> Login routes

- controllers/home-routes.js
- public/js/login.js
- public/js/logout.js
- views/layouts/main.handlebars
- views/login.handlebars
This PR adds a username field, password hiding, and jquery script to the signup form. Also fixed login bug with api reqest and added logout button to header.
> Complete signup form

- views/groupPage.handlebars
This PR refactors the group page HTML.
> Group page

- models/user.js
- views/homepage.handlebars
This PR adds a beforeBulkCreate hook to the users model to hash seeded passwords.
> beforeBulkCreate password hashing

- controllers/api/user-routes.js
- controllers/home-routes.js
- controllers/index.js
- public/js/homepage.js
- seeds/groupUserData.json
- server.js
- utils/helpers.js
- views/groupPage.handlebars
- views/homepage.handlebars
- views/layouts/main.handlebars
This PR adds groups and lists to the homepage.
> Homepage view

- config/connection.js
This PR updates the config to use jawsdb.
> updated config/connection.js

- models/index.js
Fixed case in ref of models/index.js.
> changed model index to correct

- controllers/home-routes.js
Fixed groups on homepage and security of groups.
> fixed groups on homepage

- controllers/api/list-routes.js
- public/js/listPage.js
- views/listPage.handlebars
Added functionality for users to alter the title of a list.
Also, minor code format changes.
> List Title Change

- public/js/groupPage.js
- views/groupPage.handlebars
This PR adds a simple script to the group page for claiming gifts.
> claim buttons added to list items
